[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
deposit_2024 = "Huj8fVYRHM1asSm58Zy7YuwiUYoWa9nTzj7arVK4V4Uo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/tabatrung/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
