[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
deposit_2024 = "7G5ruteouLxPrkqRo4pe8DCMw78JYo5bsnV7jyLkUFKx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/roster/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
